// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin/dashboard" | "/admin/integration" | "/admin/login" | "/admin/matches" | "/admin/players" | "/admin/results" | "/admin/settings" | "/admin/users" | "/bracket" | "/create-account" | "/dashboard" | "/explore" | "/forgot-password" | "/initial-predictions" | "/login" | "/phase-predictions" | "/predictions" | "/ranking" | "/register" | "/results" | "/standings" | "/waiting"
type AppRouteHandlerRoutes = "/api/admin/phase-lock" | "/api/admin/users/[id]/approve" | "/api/admin/users/[id]/reject" | "/api/admin/users/[id]/toggle-admin" | "/api/auth/login" | "/api/auth/logout" | "/api/auth/register" | "/api/member/predictions/champion" | "/api/member/predictions/match" | "/api/member/predictions/scorer"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin/dashboard": {}
  "/admin/integration": {}
  "/admin/login": {}
  "/admin/matches": {}
  "/admin/players": {}
  "/admin/results": {}
  "/admin/settings": {}
  "/admin/users": {}
  "/api/admin/phase-lock": {}
  "/api/admin/users/[id]/approve": { "id": string; }
  "/api/admin/users/[id]/reject": { "id": string; }
  "/api/admin/users/[id]/toggle-admin": { "id": string; }
  "/api/auth/login": {}
  "/api/auth/logout": {}
  "/api/auth/register": {}
  "/api/member/predictions/champion": {}
  "/api/member/predictions/match": {}
  "/api/member/predictions/scorer": {}
  "/bracket": {}
  "/create-account": {}
  "/dashboard": {}
  "/explore": {}
  "/forgot-password": {}
  "/initial-predictions": {}
  "/login": {}
  "/phase-predictions": {}
  "/predictions": {}
  "/ranking": {}
  "/register": {}
  "/results": {}
  "/standings": {}
  "/waiting": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
